adding SpellCraft Unity code
guptat07/SpellCraft pull request #1
Opened 2024-03-18 19:49 UTC by UnwashedPine851

2024-03-21 21:10 UTC, guptat07 requested changes
There's way too much stuff here. I don't think the demands of the project necessitate 400 files lol—I'm noticing a _ton_ of font files, assets, and demo(?) scenes that don't seem like they should be a part of the repo.

2024-03-21 21:10 UTC, guptat07 commented on SpellCraft/Assets/TextMesh Pro/Examples & Extras/Fonts/Anton OFL.txt
Are all these fonts and text files needed for our project? tbh I'm not sure where they've come from because I have used TextMeshPro before and it didn't generate any of this stuff

2024-03-25 00:21 UTC, mwong365 approved these changes

2024-04-09 00:36 UTC, guptat07 commented
@UnwashedPine851 If everything you implemented is present and working in Michael's branch, you should probably delete this branch to avoid confusion. I'm gonna close this PR. @mwong365 make a PR for your branch so that I can add it to main and start working on serial communication.

2024-04-09 00:36 UTC, closed without merging